import {HomeApp} from "start.slint";

export component DebugWindow inherits HomeApp{
	data: {
		files: [
			{name: "Peen 1",  fullPath: "<idk lol>", icon: @image-url("./Bulge.png")},
			{name: "Peen 2",  fullPath: "<idk lol>", icon: @image-url("./Bulge.png")},
			{name: "Peen 3",  fullPath: "<idk lol>", icon: @image-url("./Bulge.png")},
			{name: "Peen 4",  fullPath: "<idk lol>", icon: @image-url("./Bulge.png")},
			{name: "PP 5",    fullPath: "<idk lol>", icon: @image-url("./0001.jpg" )},
			{name: "PP 6",    fullPath: "<idk lol>", icon: @image-url("./0001.jpg" )},
			{name: "PP 7",    fullPath: "<idk lol>", icon: @image-url("./0001.jpg" )},
			{name: "PP 8",    fullPath: "<idk lol>", icon: @image-url("./0001.jpg" )},
			{name: "Peen 9",  fullPath: "<idk lol>", icon: @image-url("./Bulge.png")},
			{name: "PP 10",   fullPath: "<idk lol>", icon: @image-url("./0001.jpg" )},
			{name: "Peen 11", fullPath: "<idk lol>", icon: @image-url("./Bulge.png")},
			{name: "PP 12",   fullPath: "<idk lol>", icon: @image-url("./0001.jpg" )},
		],
		fullPath: "C:/path/thing/idk",
		status: "Data has not been loaded yet."
	};
}